@startuml Add Reservation (POST)

header Sample Coworking Sequence Diagram
title "Add Reservation (POST) + Max 3 "

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerResv
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:reservations" as controllersResv
participant "<<model>>\n:CoworkingSpace" as modelSpace
participant "<<model>>\n:Reservation" as modelResv
database "<<MongoDB>>\n:coworkingspaces" as SpacesDatabase
database "<<MongoDB>>\n:reservations" as ResvDatabase

client->server ++: req.post('/api/v1/coworkingspaces/{id}/reservations')
server->routerResv ++: router.use('/:coworkingSpaceId/reservations', reservations)
routerResv->middlewareAuth ++: protect + authorize('user','admin')
middlewareAuth-->routerResv --: next()

routerResv->controllersResv ++: addReservation()
controllersResv->modelSpace ++: findById(coworkingSpaceId)
modelSpace->SpacesDatabase ++: query
SpacesDatabase-->modelSpace --: coworkingSpace (or null)

alt coworkingSpace not found
  controllersResv->client --: 404 No CoworkingSpace
else coworkingSpace found
  controllersResv->modelResv ++: find({user: req.user.id})
  modelResv->ResvDatabase ++: query reservations by user
  ResvDatabase-->modelResv --: existedReservations[]

  alt existedReservations.length >= 3 and role != admin
    controllersResv->client --: 400 already made 3 reservations
  else allowed
    controllersResv->modelResv ++: create(req.body + user + coworkingSpace)
    modelResv->ResvDatabase ++: insert Reservation
    ResvDatabase-->modelResv --: reservation
    controllersResv<--modelResv --: reservation
    controllersResv->client --: 201 response {success, data}
  end
end

@enduml