@startuml Create CoworkingSpace (POST)

header Sample Coworking Sequence Diagram
title "Create CoworkingSpace (POST) [Admin]"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerSpaces
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:coworkingSpace" as controllersSpaces
participant "<<model>>\n:CoworkingSpace" as modelSpace
database "<<MongoDB>>\n:coworkingspaces" as SpacesDatabase

client->server ++: req.post('/api/v1/coworkingspaces')
server->routerSpaces ++: app.use('/api/v1/coworkingspaces', coworkingSpace)
routerSpaces->middlewareAuth ++: protect + authorize('admin')
middlewareAuth-->routerSpaces --: next()

routerSpaces->controllersSpaces ++: createCoworkingSpace()
controllersSpaces->modelSpace ++: create(req.body)
modelSpace->SpacesDatabase ++: CoworkingSpaceSchema
SpacesDatabase-->modelSpace --: coworkingSpace
controllersSpaces<--modelSpace --: coworkingSpace
controllersSpaces->client --: 201 response {success, data}

@enduml